# Em um mundo não tão distante...

![](imagens/farfar.jpg)

## Digamos...

Quero contabilizar os 10 primeiros numeros de fibonacci

In [12]:
n = 10
a, b, i = 0, 1, 2
fibo10 = [a, b]
while i < n :
    i = i + 1
    a, b = b, a+b
    fibo10.append(b)    

Agora quero contabilizar os 30 primeiros

In [13]:
n = 30
a, b, i = 0, 1, 2
fibo30 = [a, b]
while i < n :
    i = i + 1
    a, b = b, a+b
    fibo30.append(b)

E agora os 35 primeiros

In [14]:
n = 35
a, b, i = 0, 1, 2
fibo35 = [a, b]
while i < n :
    i = i + 1
    a, b = b, a+b
    fibo35.append(b)

# De fato funcionou

In [6]:
fibo10

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [8]:
len(fibo30)

30

In [10]:
len(fibo35)

35

# HMMM. Deve haver uma forma mais elegante

![](imagens/thinking.jpg)

# Vamos pensar em algo melhor

Será que existe alguma forma de falar algo como:

**Me de os 30 primeiros números Fibonacci!**

# Funções puras

* Necessário em linguagens **estruturadas**

* Aumenta a legibilidade do programa

* Agrupa operações relacionadas entre si

* Controla o fluxo do programa

![](imagens/funcao.png)

## Sintaxe

### Declaração

```
def nome(arg1, arg2, ...):
    escopo
    
    return var1, var2, ..., varn
```

### Chamada

```
nome(arg)
```

## Exemplo

In [33]:
def fibo(n):
    a, b, i = 0, 1, 2
    fibo = [a, b]
    while i < n :
        i = i + 1
        a, b = b, a+b
        fibo.append(b)
    
    return fibo

In [24]:
fibo(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [28]:
f15 = fibo(15)
f15

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]

Mas este programa tem um bug. Tente solicitar o `fibo(0)` ou `fibo(1)`. O que acontece?

## Exercício

Usando o que você aprendeu até agora, corrigir o programa de forma que exiba o valor esperado para os casos problemáticos.

Esperamos:

* `fibo(0)` --> lista vazia;

* `fibo(1)` --> lista contendo somente o 0;

* `fibo(2)` --> lista contendo o 0 e o 1.

* Para qualquer $ n \ge 2$ o programa deve funcionar como antes.

Um lembrete do que aprendemos até agora:

Variáveis numéricas (inteiro, flutuante, complexo), strings e listas, verificar os tipos de variáveis, declarar e designar variáveis, operações algébricas, formatação de strings, métodos e funções para tipos numéricos, strings e listas, operações com strings e listas, fatiamento e acesso por índice em listas e strings, condicionais, operadodes condicionais (< >, and, or, not, ...), estruturas condicionais (`if`, `elif`, `else`), laços condicionais (`while`), importar bibliotecas, funções matemáticas, array numérico (`numpy.array`), operações com `numpy.array`, métodos sobre o `numpy.array`, gerar gráficos com Matplotlib, que não sabemos nada, a vida é efêmera e não somos nada além de um grãozinho de areia diante a vastidão do universo.

In [30]:
# Sua resposta aqui

In [32]:
# Gabarito (consuma com responsabilidade)
#%load .resps/fibo_ok.py

# Arrays n-dimensionais

* Se comportam como tensores
    * 1D = vetor
    * 2D = matriz

* São SEMPRE unidimensionais


In [59]:
import numpy as np

In [44]:
meuarray = np.arange(24)
meuarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
meuarray.shape

(24,)

![](imagens/brain1.jpg)

In [50]:
meuarray = meuarray.reshape([2,12])
meuarray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [51]:
meuarray.shape

(2, 12)

![](imagens/brain2.jpg)

In [53]:
meuarray = meuarray.reshape([6,4])
meuarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
meuarray.shape

(6, 4)

![](imagens/brain3.jpg)

In [57]:
meuarray = meuarray.reshape([2,3,4])
meuarray

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
meuarray.shape

(2, 3, 4)

![](imagens/brain4.jpg)

##  Elementos aleatórios em arrays

In [81]:
arr_rand = np.random.rand(12)
arr_rand

array([0.38350964, 0.68546355, 0.86921601, 0.58541373, 0.40094457,
       0.88743927, 0.0895229 , 0.01731455, 0.37849994, 0.38332185,
       0.03033206, 0.77051611])

In [82]:
arr_rand = np.random.randint(-5, 5, 12)
arr_rand

array([ 4, -3,  4,  2,  3,  2,  3,  0,  3, -5, -2,  2])

In [83]:
arr_rand = np.random.randint(-10, 10, [3,4])
arr_rand

array([[ 1, -6, -6,  3],
       [-9, -4,  0, -1],
       [ 6, -5,  5, -4]])

### Identidade e diagonais

In [69]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
diagonal = np.array([1,2,3,4,5,6,7])
diagonal

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
np.diag(diagonal)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

### Matrizes *Toeplitz*

In [85]:
toeplitz = np.eye(5) + np.diag([2,2,2,2], k=1) + np.diag([3,3,3,3], k=-1)
toeplitz

array([[1., 2., 0., 0., 0.],
       [3., 1., 2., 0., 0.],
       [0., 3., 1., 2., 0.],
       [0., 0., 3., 1., 2.],
       [0., 0., 0., 3., 1.]])

## Índices e Fatias de arrays n-dimensionais

    Operando com submatrizes
    fancy indexing

# Laço `for`

    Laços temporais e espaciais
    arange e range
    funcoes bidimensionais

# Gráficos

## Gráficos de função

## Gráficos de dispersão

## Gráficos em barra

## Gráficos em setor

## Histogramas

# Performance

    fromfile
    loadtxt
    ufunc
    broadcasting    for loop
    multiplicacao matricial
    